/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'makotan' at '15/09/19 10:36' with Gradle 2.6
 *
 * @author makotan, @date 15/09/19 10:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
